### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by ntcho** [yaosamo/personal-website#46]
Hi! I really enjoyed your personal website. It's so well designed but also very informative.

By the way, I think there is a typo on the footer:

https://github.com/yaosamo/personal-website/blob/0e974315f454a9359e27240f8a5da2ff15ed18c4/components/layout.js#L16

Maybe `have a nice day!` was the intended text?

**Comment by yaosamo** [comment]
@ntcho wow you created an issue here! Thank you so much! Ha no it actually what I meant just "have a nice" whatever it is for a person :)
